[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"DefaultSession" 
"SessionRX_E1_E20_SYSTEM" 
[CONFIGURATIONS]
"8BAY_ENERSYS_EU" 
"8BAY_ENERSYS_US" 
"8BAY_EU_SUISSE" 
"8BAY_HAWKER_US" 
"Debug" 
"DEMO" 
"EU_LIMIT_2900W" 
"SAVOYE" 
[CURRENT_CONFIGURATION]
"Debug" 
[CURRENT_SESSION]
"SessionRX_E1_E20_SYSTEM" 
[GENERAL_DATA_PROJECT]
[GENERAL_DATA_CONFIGURATION_8BAY_ENERSYS_EU]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_8BAY_ENERSYS_EU]
"DefaultSession" 
"SessionRX_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_8BAY_ENERSYS_US]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_8BAY_ENERSYS_US]
"DefaultSession" 
"SessionRX_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_8BAY_EU_SUISSE]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_8BAY_EU_SUISSE]
"DefaultSession" 
"SessionRX_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_8BAY_HAWKER_US]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_8BAY_HAWKER_US]
"DefaultSession" 
"SessionRX_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Debug]
"DefaultSession" 
"SessionRX_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_DEMO]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_DEMO]
"DefaultSession" 
"SessionRX_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_EU_LIMIT_2900W]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_EU_LIMIT_2900W]
"DefaultSession" 
"SessionRX_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_SAVOYE]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_SAVOYE]
"DefaultSession" 
"SessionRX_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_SESSION_SAVOYE_SessionRX_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_DEMO_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_EU_LIMIT_2900W_SessionRX_E1_E20_SYSTEM]
[GENERAL_DATA_SESSION_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_8BAY_ENERSYS_US_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_8BAY_ENERSYS_EU_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_EU_LIMIT_2900W_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_8BAY_HAWKER_US_SessionRX_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_8BAY_ENERSYS_EU_SessionRX_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_SAVOYE_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_8BAY_EU_SUISSE_SessionRX_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_8BAY_HAWKER_US_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_DEMO_SessionRX_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_SessionRX_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_8BAY_ENERSYS_US_SessionRX_E1_E20_SYSTEM]
[GENERAL_DATA_SESSION_SessionRX_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_8BAY_EU_SUISSE_DefaultSession]
[END]
