/***********************************************************************/
/*                                                                     */
/*  FILE        :dbsct.c                                               */
/*  DATE        :Mon, Jul 06, 2009                                     */
/*  DESCRIPTION :Setting of B,R Section                                */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.13).    */
/*                                                                     */
/***********************************************************************/

/* $Id$ */

#include "typedefine.h"

#pragma unpack

/* Section start */

#pragma section $DSEC
extern const struct {
	_UBYTE *rom_s;       /* Start address of the initialized data section in ROM */
	_UBYTE *rom_e;       /* End address of the initialized data section in ROM   */
	_UBYTE *ram_s;       /* Start address of the initialized data section in RAM */
}   _DTBL[] = {
		{ __sectop("D"),            __secend("D"),              __sectop("R") },
		{ __sectop("D_2"),          __secend("D_2"),            __sectop("R_2") },
		{ __sectop("D_1"),          __secend("D_1"),            __sectop("R_1") },
		{ __sectop("D_usblib"),     __secend("D_usblib"),       __sectop("R_usblib") },
		{ __sectop("D_hcd"),        __secend("D_hcd"),          __sectop("R_hcd") },
		{ __sectop("D_pcd"),        __secend("D_pcd"),          __sectop("R_pcd") },
		{ __sectop("D_descriptor"), __secend("D_descriptor"),   __sectop("R_descriptor") },
		{ __sectop("D_hub"),        __secend("D_hub"),          __sectop("R_hub") },
		{ __sectop("D_eletest"),    __secend("D_eletest"),      __sectop("R_eletest") },
		{ __sectop("D_smpl"),       __secend("D_smpl"),         __sectop("R_smpl") },
		{ __sectop("D_ansi"),       __secend("D_ansi"),         __sectop("R_ansi") },
		{ __sectop("D_Dummy"),      __secend("D_Dummy"),        __sectop("R_Dummy") },
		{ __sectop("D_testdata"),   __secend("D_testdata"),     __sectop("R_testdata") },

		// nonOS
		{ __sectop("D_schedule"),   __secend("D_schedule"),     __sectop("R_schedule") },
		{ __sectop("D_rx_rsk"),     __secend("D_rx_rsk"),       __sectop("R_rx_rsk") },

		// DTC table
		{ __sectop("D_DTCtable"),   __secend("D_DTCtable"),     __sectop("R_DTCtable") },

		// HMSC
		{ __sectop("D_hmsc"),       __secend("D_hmsc"),         __sectop("R_hmsc") },
};

#pragma section $BSEC
extern const struct {
	_UBYTE *b_s;         /* Start address of non-initialized data section */
	_UBYTE *b_e;         /* End address of non-initialized data section */
}   _BTBL[] = {
		{ __sectop("B"),            __secend("B") },
		{ __sectop("B_2"),          __secend("B_2") },
		{ __sectop("B_1"),          __secend("B_1") },
		{ __sectop("B_usblib"),     __secend("B_usblib") },
		{ __sectop("B_hcd"),        __secend("B_hcd") },
		{ __sectop("B_pcd"),        __secend("B_pcd") },
		{ __sectop("B_descriptor"), __secend("B_descriptor") },
		{ __sectop("B_hub"),        __secend("B_hub") },
		{ __sectop("B_eletest"),    __secend("B_eletest") },
		{ __sectop("B_smpl"),       __secend("B_smpl") },
		{ __sectop("B_ansi"),       __secend("B_ansi") },
		{ __sectop("B_Dummy"),      __secend("B_Dummy") },
		{ __sectop("B_testdata"),   __secend("B_testdata") },
		{ __sectop("B_ansi"),       __secend("B_ansi") },

		// nonOS
		{ __sectop("B_schedule"),   __secend("B_schedule") },
		{ __sectop("B_rx_rsk"),     __secend("B_rx_rsk") },

		// DTC table
		{ __sectop("B_DTCtable"),   __secend("B_DTCtable") },

		// HMSC
		{ __sectop("B_hmsc"),       __secend("B_hmsc") },
};

#pragma section

/*
 ** CTBL prevents excessive output of L1100 messages when linking.
 ** Even if CTBL is deleted, the operation of the program does not change.
 */
_UBYTE *_CTBL[] = {
		__sectop("H"),
		__sectop("C_1"), __sectop("C_2"), __sectop("C"),
		__sectop("W_1"), __sectop("W_2"), __sectop("W")
};

#pragma packoption
